### ISSUE TITLE
musl build is not static

### ISSUE THREAD

**Issue by zegervdv** [lukas-reineke/cbfmt#4]
The musl build in the releases is not statically built, it seems to be the same as the linux build.

I think the `--target=x86_64-unknown-linux-musl` option is needed for `cargo build` .

**Comment by lukas-reineke** [comment]
I think it should be fixed now

**Comment by zegervdv** [comment]
Not completely, I'm getting a segfault now.
`ldd` reports `/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./cbfmt_linux-x86_64-musl_v0.1.1-1/cbfmt)`
But I need to look into it further.

**Comment by lukas-reineke** [comment]
Hm maybe treesitter needs an actual musl C++ compiler to work then.

I cheated and used the normal one, because afaik there is no easy way to get that on the Ubuntu runner

This might be a lot more complicated then

**Comment by zegervdv** [comment]
I see. Might the `musl-tools` package not provide when you need?

**Comment by lukas-reineke** [comment]
No, it's not in musl-tools

**Comment by zegervdv** [comment]
I've had some luck compiling it in an alpine linux container, but it's not completely static yet.
I'll try to look into it some more detail over the weekend

**Comment by lukas-reineke** [comment]
GitHub doesn't offer alpine runners. You'd have to self host, and I don't want to do that

**Comment by zegervdv** [comment]
Ah, didn't know that.
Why is this so hard :)

**Comment by zegervdv** [comment]
I think I found a way: https://github.com/messense/cargo-zigbuild

After installing this and running cargo zigbuild —target x86_64-unknown-linux-musl —release 
I got a fully static build that works.

**Comment by zegervdv** [comment]
Also had to pip3 install ziglang for that to work

**Comment by lukas-reineke** [comment]
Looks promising.
I just started a new job, I am pretty busy right now. I'll look into this when I find some time.
If you have it working, you could also open a PR
